/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noveena;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sachindra
 */
public class AddItems extends javax.swing.JFrame {
    
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

    /**
     * Creates new form AddItems
     */
    public AddItems() {
        initComponents();
        this.setAlwaysOnTop(false);
        this.setLocationRelativeTo(null);
        

        
        con = DBconnect.connect();
        
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(radioItemId);
        bg1.add(radioItemName);
        bg1.add(radioItemMake);
        tableRefresh();
        
        
    }

    
    
        public void tableLoad(String text,String selection){
            String sql="";
        try {
            if (selection=="Make") {
                sql = "SELECT ItemID,ItemName,Make,Model,Deposit,RentCharge,Availability From rentitem WHERE "+selection+" LIKE '%"+text+"%'"; 
            }
            else if (selection=="ItemName") {
                sql = "SELECT ItemID,ItemName,Make,Model,Deposit,RentCharge,Availability From rentitem WHERE "+selection+" LIKE '%"+text+"%'";  
            }
            else if (selection=="ItemID") {   
                sql = "SELECT ItemID,ItemName,Make,Model,Deposit,RentCharge,Availability From rentitem WHERE "+selection+" ='"+text+"'";
            }
            System.out.println(sql);
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
    }
        
        public void tableRefresh(){
        
        try {
            String sql = "SELECT * FROM rentitem ORDER BY ItemID";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
        
        
        
        public void clear(){
            ButtonGroup bg1 = new ButtonGroup( );
            bg1.add(radioItemId);
            bg1.add(radioItemName);
            bg1.add(radioItemMake);
            bg1.clearSelection();
            txtDeposit.setText(null);
            txtItemID.setText(null);
            txtItemName.setText(null);
            txtMake.setText(null);
            txtModel.setText(null);
            txtRentCharge.setText(null);
            txtSearch.setText(null);
            comboAvailability.setSelectedIndex(0);
            
        }
        
        public void clearLabel(){
            lblErr1.setText(null);
            lblErr2.setText(null);
            lblErr3.setText(null);
            lblErr4.setText(null);
            lblErr5.setText(null);
            lblErr6.setText(null);
            lblErr7.setText(null);
            lblErr8.setText(null);
        }
        
        public void clearTable(){
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
            model.setRowCount(0);
        }
        
        
        public boolean ValidItemID( String ItemID){
        
        try {
                String sql = "SELECT ItemID From rentitem WHERE ItemID ='"+ItemID+"'"; 
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                    while (rs.next()) {  
                                if(ItemID.equals(rs.getString("ItemID"))){
                                    return true;
                                    
                                }
                    }
        } catch (Exception e) {
        }
        return false;            
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtRentCharge = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        radioItemId = new javax.swing.JRadioButton();
        radioItemName = new javax.swing.JRadioButton();
        radioItemMake = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        bntDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnClear = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        comboAvailability = new javax.swing.JComboBox<>();
        lblErr1 = new javax.swing.JLabel();
        lblErr2 = new javax.swing.JLabel();
        lblErr3 = new javax.swing.JLabel();
        lblErr4 = new javax.swing.JLabel();
        lblErr5 = new javax.swing.JLabel();
        lblErr6 = new javax.swing.JLabel();
        lblErr8 = new javax.swing.JLabel();
        lblErr7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        setResizable(false);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Rent Charge :");

        txtRentCharge.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtRentCharge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRentChargeFocusLost(evt);
            }
        });
        txtRentCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentChargeActionPerformed(evt);
            }
        });

        txtDeposit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDeposit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepositFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Deposit :");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Model :");

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtModel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelFocusLost(evt);
            }
        });
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Make :");

        txtMake.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMake.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMakeFocusLost(evt);
            }
        });

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Item Name :");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Item ID :");

        txtItemID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtItemID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemIDFocusLost(evt);
            }
        });
        txtItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIDActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        radioItemId.setText("Item ID");

        radioItemName.setText("Item Name");

        radioItemMake.setText("Item Make");
        radioItemMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemMakeActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Make", "Model", "Deposit", "Rent Charge", "Availability"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnUpdate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        bntDelete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bntDelete.setText("Delete");
        bntDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel8.setText("Add Items");

        title.setBackground(new java.awt.Color(102, 102, 102));
        title.setAlignmentX(0.0F);
        title.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rent Items Management System");

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noveena/126001-matte-white-square-icon-symbols-shapes-minimize (Custom).png"))); // NOI18N
        minimizeButton.setToolTipText("minimize");
        minimizeButton.setBorder(null);
        minimizeButton.setBorderPainted(false);
        minimizeButton.setFocusPainted(false);
        minimizeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noveena/close-icon-16 (Custom).png"))); // NOI18N
        exitButton.setToolTipText("exit");
        exitButton.setPreferredSize(new java.awt.Dimension(30, 30));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noveena/noveena_logo (Mobile) (Custom) (Custom).png"))); // NOI18N

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(512, 512, 512)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titleLayout.createSequentialGroup()
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titleLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnClear.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setText("Availability :");

        comboAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Available", "Not Available" }));
        comboAvailability.setPreferredSize(new java.awt.Dimension(88, 22));
        comboAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAvailabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(669, 669, 669)
                        .addComponent(radioItemId)
                        .addGap(35, 35, 35)
                        .addComponent(radioItemName)
                        .addGap(18, 18, 18)
                        .addComponent(radioItemMake)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(482, 482, 482)
                        .addComponent(lblErr8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(lblErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(lblErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(lblErr3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(lblErr4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblErr5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtRentCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(lblErr7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(71, 71, 71)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblErr6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(comboAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(298, 298, 298)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(bntDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioItemId)
                            .addComponent(radioItemName)
                            .addComponent(radioItemMake)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErr8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblErr3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblErr4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(lblErr5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(txtRentCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErr6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(comboAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(lblErr7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bntDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lblErr7.setText(null);
        
        String ItemID = txtItemID.getText();
        String ItemName = txtItemName.getText();
        String Make = txtMake.getText();
        String Model = txtModel.getText();
        String Deposit = txtDeposit.getText();
        String RentCharge = txtRentCharge.getText();
        String Availability = comboAvailability.getSelectedItem().toString();
        
        if (ItemID.isEmpty() || ItemName.isEmpty() || Make.isEmpty() || Model.isEmpty() || Deposit.isEmpty() || RentCharge.isEmpty() || Availability.equals("Select")) {
                if(Availability.equals("Select")){
                lblErr7.setText("Availability Not Selected");
            }
            JOptionPane.showMessageDialog(null,"One or More Filelds Are Empty","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        else if (ValidItemID(ItemID)) {
            JOptionPane.showMessageDialog(null,"Item ID Already Exist","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!ValidItemID(ItemID) && Validation.ValidTextOnly(Make) && Validation.ValidTextOnly(ItemName) && Validation.ValidTextAndDigits(Model) && Validation.ValidDigits(Deposit) && Validation.ValidDigits(RentCharge) && !Availability.equals("Select")){
                        try {
                            String query1 = "INSERT INTO rentitem (ItemID,ItemName,Make,Model,Deposit,RentCharge,Availability) VALUES ('"+ItemID+"', '"+ItemName+"', '"+Make+"', '"+Model+"', '"+Deposit+"', '"+RentCharge+"','"+Availability+"' )";
                            ps = con.prepareStatement(query1);
                            ps.execute();
                            JOptionPane.showMessageDialog(null,"Successfully Added","Success",JOptionPane.INFORMATION_MESSAGE);
                            btnClearActionPerformed(evt);
                                    
                        } catch (Exception e) {
                            System.out.println(e);
                        }  
        }
        else
            JOptionPane.showMessageDialog(null,"One Or More Fields Are Invalid","Error",JOptionPane.ERROR_MESSAGE);
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void radioItemMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioItemMakeActionPerformed

    private void txtRentChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentChargeActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(RentItemInteface.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        lblErr8.setText(null);
        String Search = txtSearch.getText();
        
        if (radioItemId.isSelected() || radioItemMake.isSelected() || radioItemName.isSelected()) {
            if (Validation.ValidTextAndDigits(Search)) {
                    if (radioItemId.isSelected()) {
                        tableLoad(Search,"ItemID");
                    }
                    else if(radioItemMake.isSelected()){
                        tableLoad(Search,"Make");
                    }
                    else if(radioItemName.isSelected()){
                        tableLoad(Search,"ItemName");
                    }
                    }
                    else
                        lblErr8.setText("*Invalid");  
        }
        else{
            JOptionPane.showMessageDialog(null,"No Option Selected","Error",JOptionPane.ERROR_MESSAGE);
                     
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        btnAdd.setEnabled(false);
        txtItemID.setEditable(false);
        int row= jTable1.getSelectedRow();
        
        String ItemID = jTable1.getValueAt(row, 0).toString();
        String ItemName = jTable1.getValueAt(row, 1).toString();
        String Make = jTable1.getValueAt(row, 2).toString();
        String Model = jTable1.getValueAt(row, 3).toString();
        String Deposit = jTable1.getValueAt(row, 4).toString();
        String RentCharge = jTable1.getValueAt(row, 5).toString();
        String Availability = jTable1.getValueAt(row, 6).toString();
        
        txtItemID.setText(ItemID);
        txtItemName.setText(ItemName);
        txtMake.setText(Make);
        txtModel.setText(Model);
        txtDeposit.setText(Deposit);
        txtRentCharge.setText(RentCharge);
        comboAvailability.setSelectedItem(Availability);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAvailabilityActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
        clearLabel();
        tableRefresh();
        btnAdd.setEnabled(true);
        txtItemID.setEditable(true);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String ItemID = txtItemID.getText();
        String ItemName = txtItemName.getText();
        String Make = txtMake.getText();
        String Model = txtModel.getText();
        String Deposit = txtDeposit.getText();
        String RentCharge = txtRentCharge.getText();
        String Availability = comboAvailability.getSelectedItem().toString();
        
        
        try {
           
                String query1 = "UPDATE rentitem SET ItemName ='"+ItemName+"', Make ='"+Make+"', Model ='"+Model+"', Deposit ='"+Deposit+"', RentCharge ='"+RentCharge+"', Availability ='"+Availability+"'  WHERE ItemID ="+ItemID+" ";
                
                ps = con.prepareStatement(query1);
                ps.execute();
                JOptionPane.showMessageDialog(null,"Successfully Updated","Success",JOptionPane.INFORMATION_MESSAGE);
                btnClearActionPerformed(evt);
                
               
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void bntDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeleteActionPerformed
        int row= jTable1.getSelectedRow();
        String ItemID = jTable1.getValueAt(row, 0).toString();
        
        try {
                String query2 = "DELETE FROM rentitem WHERE ItemID ='"+ItemID+"'";
                ps = con.prepareStatement(query2);
                ps.execute();
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
        btnClearActionPerformed(evt);
    }//GEN-LAST:event_bntDeleteActionPerformed

    private void txtItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemIDActionPerformed

    private void txtItemIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemIDFocusLost
          String ItemID = txtItemID.getText();
        
        if (Validation.ValidDigits(ItemID) || ItemID.isEmpty()) {
            lblErr1.setText("");
        }
        else
            lblErr1.setText("*Invalid");
    
    }//GEN-LAST:event_txtItemIDFocusLost

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        
        String ItemName = txtItemName.getText();
        
        
            if (Validation.ValidTextOnly(ItemName) || ItemName.isEmpty()) {
            lblErr2.setText("");
        }
            else
            lblErr2.setText("*Invalid");
        
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtMakeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMakeFocusLost
        String Make = txtMake.getText();
        
        
            if (Validation.ValidTextOnly(Make) || Make.isEmpty()) {
            lblErr3.setText("");
        }
            else
            lblErr3.setText("*Invalid");
        
    }//GEN-LAST:event_txtMakeFocusLost

    private void txtModelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelFocusLost
        String Model = txtModel.getText();
        
            if (Validation.ValidTextAndDigits(Model) || Model.isEmpty()) {
            lblErr4.setText("");
        }
            else
            lblErr4.setText("*Invalid");
        
        
        
    }//GEN-LAST:event_txtModelFocusLost

    private void txtDepositFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositFocusLost
        String Deposit = txtDeposit.getText();
        
            if (Validation.ValidDigits(Deposit) || Deposit.isEmpty()) {
            lblErr5.setText("");
        }
            else
            lblErr5.setText("*Invalid");
        
    }//GEN-LAST:event_txtDepositFocusLost

    private void txtRentChargeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRentChargeFocusLost
        String RentCharge = txtRentCharge.getText();
        
            if (Validation.ValidDigits(RentCharge) || RentCharge.isEmpty()) {
            lblErr6.setText("");
        }
            else
            lblErr6.setText("*Invalid");
        
    }//GEN-LAST:event_txtRentChargeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDelete;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboAvailability;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErr1;
    private javax.swing.JLabel lblErr2;
    private javax.swing.JLabel lblErr3;
    private javax.swing.JLabel lblErr4;
    private javax.swing.JLabel lblErr5;
    private javax.swing.JLabel lblErr6;
    private javax.swing.JLabel lblErr7;
    private javax.swing.JLabel lblErr8;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JRadioButton radioItemId;
    private javax.swing.JRadioButton radioItemMake;
    private javax.swing.JRadioButton radioItemName;
    private javax.swing.JPanel title;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRentCharge;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
